//! Markdown campaign report.
//!
//! After a discover -> harness -> run -> triage cycle, [`render_markdown`]
//! composes a detailed, self-contained Markdown document summarizing the
//! campaign: the target, run configuration, coverage, corpus, and every triaged
//! crash (CASR severity + LLM bug report). The output is plain `CommonMark`
//! with `GitHub`-flavored tables, so it pastes into any Markdown tool unchanged.
//!
//! [`ReportData`] is an owned snapshot with no store/runtime references, so the
//! renderer is a pure function and fully unit-testable;
//! [`crate::ServiceContainer::generate_report`] gathers it from the store,
//! coverage, and workspace.

use std::fmt::Write as _;

use hf_core::crash::{Crash, CrashSeverity};
use hf_core::target::TargetCandidate;
use hf_coverage::CoverageSummary;
use hf_storage::RunRecord;

/// Corpus composition for the report.
#[derive(Debug, Clone, Copy, Default)]
pub struct CorpusStats {
    pub count: usize,
    pub total_bytes: u64,
    pub seeds: usize,
    pub from_fuzzer: usize,
    pub minimized: usize,
}

/// An owned snapshot of everything a campaign report renders. Gathered by
/// [`crate::ServiceContainer::generate_report`]; rendered by [`render_markdown`].
#[derive(Debug, Clone)]
pub struct ReportData {
    /// RFC3339 timestamp the report was generated.
    pub generated_at: String,
    /// Project root path (as configured).
    pub project: String,
    /// Target symbol the campaign fuzzed.
    pub target: String,
    /// `hobot_fuzz` version that produced the report.
    pub tool_version: String,
    /// The discovered target, if it could be resolved.
    pub candidate: Option<TargetCandidate>,
    /// The most recent run for the project, if any.
    pub run: Option<RunRecord>,
    /// Triaged, deduplicated crashes for the run.
    pub crashes: Vec<Crash>,
    /// Line/function/region coverage, if it could be computed.
    pub coverage: Option<CoverageSummary>,
    /// Number of project functions covered by the corpus.
    pub covered_functions: usize,
    /// Corpus composition.
    pub corpus: CorpusStats,
}

/// Render a campaign report as GitHub-flavored Markdown.
#[must_use]
pub fn render_markdown(data: &ReportData) -> String {
    let mut md = String::with_capacity(4096);

    let _ = writeln!(md, "# Fuzzing Report: `{}`", data.target);
    let _ = writeln!(md);
    let _ = writeln!(md, "| | |");
    let _ = writeln!(md, "|---|---|");
    let _ = writeln!(md, "| Project | `{}` |", data.project);
    let _ = writeln!(md, "| Target | `{}` |", data.target);
    let _ = writeln!(md, "| Generated | {} |", data.generated_at);
    let _ = writeln!(md, "| Tool | hobot_fuzz {} |", data.tool_version);
    let _ = writeln!(md);

    render_executive_summary(&mut md, data);
    render_visual_summary(&mut md, data);
    render_target(&mut md, data);
    render_run(&mut md, data);
    render_coverage(&mut md, data);
    render_corpus(&mut md, data);
    render_findings(&mut md, data);

    let _ = writeln!(md, "---");
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "_Generated by hobot_fuzz {} on {}._",
        data.tool_version, data.generated_at
    );
    md
}

fn render_executive_summary(md: &mut String, data: &ReportData) {
    let _ = writeln!(md, "## Executive Summary");
    let _ = writeln!(md);

    let total = data.crashes.len();
    let exploitable = data
        .crashes
        .iter()
        .filter(|c| {
            matches!(
                c.casr.as_ref().map(|r| r.severity),
                Some(CrashSeverity::Exploitable | CrashSeverity::ProbablyExploitable)
            )
        })
        .count();
    let status = data.run.as_ref().map_or_else(
        || "no run recorded".to_owned(),
        |r| format!("{:?}", r.status),
    );
    let engine = data
        .run
        .as_ref()
        .map_or_else(|| "n/a".to_owned(), |r| format!("{:?}", r.engine));
    let cov = data.coverage.map_or_else(
        || "not available".to_owned(),
        |c| format!("{:.1}% lines", c.line_percent()),
    );

    if total == 0 {
        let _ = writeln!(
            md,
            "No crashes were found in the most recent campaign (engine {engine}, status {status})."
        );
    } else {
        let _ = writeln!(
            md,
            "The campaign surfaced **{total} unique crash(es)**, of which **{exploitable}** \
             rank as exploitable or probably exploitable (engine {engine}, status {status})."
        );
    }
    let _ = writeln!(md);
    let _ = writeln!(md, "- Unique crashes: **{total}**");
    let _ = writeln!(
        md,
        "- Exploitable / probably exploitable: **{exploitable}**"
    );
    let _ = writeln!(md, "- Line coverage: **{cov}**");
    let _ = writeln!(
        md,
        "- Corpus: **{} input(s)**, {}",
        data.corpus.count,
        human_bytes(data.corpus.total_bytes)
    );
    let _ = writeln!(md);
}

/// Visual summary: graphs that render in any Markdown tool (Mermaid charts for
/// rich viewers, plus Unicode bars that render literally everywhere).
fn render_visual_summary(md: &mut String, data: &ReportData) {
    let _ = writeln!(md, "## Visual Summary");
    let _ = writeln!(md);

    // Coverage bars (universal) first, then Mermaid charts (rich viewers).
    if let Some(c) = data.coverage {
        let _ = writeln!(md, "**Coverage**");
        let _ = writeln!(md);
        let _ = writeln!(md, "```text");
        let _ = writeln!(md, "Lines     {}", coverage_bar(c.line_percent()));
        let _ = writeln!(md, "Functions {}", coverage_bar(c.function_percent()));
        let _ = writeln!(md, "Regions   {}", coverage_bar(c.region_percent()));
        let _ = writeln!(md, "```");
        let _ = writeln!(md);
        let _ = writeln!(md, "{}", coverage_mermaid(c));
        let _ = writeln!(md);
    }

    // Severity distribution pie (only meaningful with crashes).
    if !data.crashes.is_empty() {
        let _ = writeln!(md, "{}", severity_pie_mermaid(&data.crashes));
        let _ = writeln!(md);
        let _ = writeln!(md, "{}", kind_pie_mermaid(&data.crashes));
        let _ = writeln!(md);
    }

    if data.coverage.is_none() && data.crashes.is_empty() {
        let _ = writeln!(md, "_No coverage or crash data yet to visualize._");
        let _ = writeln!(md);
    }
}

/// A 20-cell Unicode block bar with a trailing percentage, e.g.
/// `████████████░░░░░░░░  60.0%`.
fn coverage_bar(percent: f64) -> String {
    const CELLS: usize = 20;
    let filled = ((percent / 100.0) * CELLS as f64).round() as usize;
    let filled = filled.min(CELLS);
    let bar: String = "█".repeat(filled) + &"░".repeat(CELLS - filled);
    format!("{bar}  {percent:.1}%")
}

/// A Mermaid bar chart of coverage percentages.
fn coverage_mermaid(c: CoverageSummary) -> String {
    format!(
        "```mermaid\n\
         xychart-beta\n\
         \x20   title \"Coverage (%)\"\n\
         \x20   x-axis [Lines, Functions, Regions]\n\
         \x20   y-axis \"Percent covered\" 0 --> 100\n\
         \x20   bar [{:.1}, {:.1}, {:.1}]\n\
         ```",
        c.line_percent(),
        c.function_percent(),
        c.region_percent()
    )
}

/// A Mermaid pie chart of crash exploitability (CASR severity).
fn severity_pie_mermaid(crashes: &[Crash]) -> String {
    let mut exploitable = 0;
    let mut probably = 0;
    let mut not_exploitable = 0;
    let mut undefined = 0;
    for c in crashes {
        match c.casr.as_ref().map(|r| r.severity) {
            Some(CrashSeverity::Exploitable) => exploitable += 1,
            Some(CrashSeverity::ProbablyExploitable) => probably += 1,
            Some(CrashSeverity::NotExploitable) => not_exploitable += 1,
            _ => undefined += 1,
        }
    }
    let mut out = String::from("```mermaid\npie showData\n    title Crash severity\n");
    for (label, n) in [
        ("Exploitable", exploitable),
        ("Probably exploitable", probably),
        ("Not exploitable", not_exploitable),
        ("Undefined", undefined),
    ] {
        if n > 0 {
            let _ = writeln!(out, "    \"{label}\" : {n}");
        }
    }
    out.push_str("```");
    out
}

/// A Mermaid pie chart of crash kinds (ASan/UBSan/SEGV/...).
fn kind_pie_mermaid(crashes: &[Crash]) -> String {
    let mut counts: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
    for c in crashes {
        *counts.entry(format!("{:?}", c.kind)).or_default() += 1;
    }
    let mut out = String::from("```mermaid\npie showData\n    title Crash kinds\n");
    for (label, n) in counts {
        let _ = writeln!(out, "    \"{label}\" : {n}");
    }
    out.push_str("```");
    out
}

fn render_target(md: &mut String, data: &ReportData) {
    let _ = writeln!(md, "## Target");
    let _ = writeln!(md);
    let Some(c) = &data.candidate else {
        let _ = writeln!(md, "_Target metadata was not available (not discovered)._");
        let _ = writeln!(md);
        return;
    };
    let _ = writeln!(md, "| Property | Value |");
    let _ = writeln!(md, "|---|---|");
    let _ = writeln!(md, "| Symbol | `{}` |", c.symbol);
    let _ = writeln!(md, "| Kind | {:?} |", c.kind);
    let _ = writeln!(md, "| Language | {:?} |", c.language);
    let _ = writeln!(
        md,
        "| Location | `{}:{}:{}` |",
        c.location.file.display(),
        c.location.line,
        c.location.col
    );
    if let Some(sig) = &c.signature {
        let _ = writeln!(md, "| Signature | `{sig}` |");
    }
    let _ = writeln!(md, "| Input surface | {:?} |", c.input_surface);
    let _ = writeln!(md, "| Complexity | {} |", c.complexity);
    let _ = writeln!(
        md,
        "| Accumulated complexity | {} |",
        c.accumulated_complexity
    );
    let _ = writeln!(
        md,
        "| Reachable functions | {} |",
        c.reachable_functions.len()
    );
    let _ = writeln!(md, "| Fit score | {:.2} |", c.fit_score);
    let _ = writeln!(md);
    if !c.rationale.trim().is_empty() {
        let _ = writeln!(md, "> {}", c.rationale.trim());
        let _ = writeln!(md);
    }
}

fn render_run(md: &mut String, data: &ReportData) {
    let _ = writeln!(md, "## Run");
    let _ = writeln!(md);
    let Some(r) = &data.run else {
        let _ = writeln!(md, "_No run has been recorded for this project._");
        let _ = writeln!(md);
        return;
    };
    let _ = writeln!(md, "| Property | Value |");
    let _ = writeln!(md, "|---|---|");
    let _ = writeln!(md, "| Engine | {:?} |", r.engine);
    let _ = writeln!(md, "| Status | {:?} |", r.status);
    let _ = writeln!(md, "| Started | {} |", r.started_at.to_rfc3339());
    if let Some(ended) = r.ended_at {
        let _ = writeln!(md, "| Ended | {} |", ended.to_rfc3339());
        let secs = (ended - r.started_at).num_seconds().max(0);
        let _ = writeln!(md, "| Duration | {} |", human_duration(secs));
    }
    if let Some(cfg) = &r.config {
        let _ = writeln!(md, "| Sanitizer | {:?} |", cfg.sanitizer);
        if let Some(d) = cfg.duration {
            let budget = i64::try_from(d.as_secs()).unwrap_or(i64::MAX);
            let _ = writeln!(md, "| Budget | {} |", human_duration(budget));
        }
    }
    let _ = writeln!(md);
}

fn render_coverage(md: &mut String, data: &ReportData) {
    let _ = writeln!(md, "## Coverage");
    let _ = writeln!(md);
    let Some(c) = data.coverage else {
        let _ = writeln!(
            md,
            "_Coverage was not available (no harness built, or coverage tooling absent)._"
        );
        let _ = writeln!(md);
        return;
    };
    let _ = writeln!(md, "| Metric | Covered | Total | Percent |");
    let _ = writeln!(md, "|---|---:|---:|---:|");
    let _ = writeln!(
        md,
        "| Lines | {} | {} | {:.1}% |",
        c.lines_covered,
        c.lines_total,
        c.line_percent()
    );
    let _ = writeln!(
        md,
        "| Functions | {} | {} | {:.1}% |",
        c.functions_covered,
        c.functions_total,
        c.function_percent()
    );
    let _ = writeln!(
        md,
        "| Regions | {} | {} | {:.1}% |",
        c.regions_covered,
        c.regions_total,
        c.region_percent()
    );
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "{} project function(s) are exercised by the corpus.",
        data.covered_functions
    );
    let _ = writeln!(md);
}

fn render_corpus(md: &mut String, data: &ReportData) {
    let s = &data.corpus;
    let _ = writeln!(md, "## Corpus");
    let _ = writeln!(md);
    let _ = writeln!(md, "| Property | Value |");
    let _ = writeln!(md, "|---|---|");
    let _ = writeln!(md, "| Entries | {} |", s.count);
    let _ = writeln!(md, "| Total size | {} |", human_bytes(s.total_bytes));
    let _ = writeln!(md, "| Seeds | {} |", s.seeds);
    let _ = writeln!(md, "| From fuzzer | {} |", s.from_fuzzer);
    let _ = writeln!(md, "| Minimized | {} |", s.minimized);
    let _ = writeln!(md);
}

fn render_findings(md: &mut String, data: &ReportData) {
    let _ = writeln!(md, "## Findings");
    let _ = writeln!(md);
    if data.crashes.is_empty() {
        let _ = writeln!(md, "No crashes were found. There is nothing to triage.");
        let _ = writeln!(md);
        return;
    }

    // Summary table.
    let _ = writeln!(md, "| # | Kind | Severity | Location | Signature |");
    let _ = writeln!(md, "|---:|---|---|---|---|");
    for (i, c) in data.crashes.iter().enumerate() {
        let severity = c
            .casr
            .as_ref()
            .map_or_else(|| "Undefined".to_owned(), |r| format!("{:?}", r.severity));
        let location = c
            .casr
            .as_ref()
            .map(|r| r.crashline.clone())
            .filter(|l| !l.is_empty())
            .unwrap_or_else(|| "-".to_owned());
        let _ = writeln!(
            md,
            "| {} | {:?} | {} | `{}` | `{}` |",
            i + 1,
            c.kind,
            severity,
            location,
            truncate(&c.stack_signature, 60)
        );
    }
    let _ = writeln!(md);

    // Per-crash detail.
    for (i, c) in data.crashes.iter().enumerate() {
        render_crash_detail(md, i + 1, c);
    }
}

fn render_crash_detail(md: &mut String, n: usize, c: &Crash) {
    let title = c
        .bug_report
        .as_ref()
        .map(|b| b.title.clone())
        .filter(|t| !t.trim().is_empty())
        .unwrap_or_else(|| c.summary.clone());
    let _ = writeln!(md, "### Finding {n}: {title}");
    let _ = writeln!(md);
    let _ = writeln!(md, "- Kind: `{:?}`", c.kind);
    let _ = writeln!(md, "- Stack signature: `{}`", c.stack_signature);
    let _ = writeln!(md, "- Input: `{}`", c.input_path.display());
    let _ = writeln!(
        md,
        "- Minimized: {}",
        if c.minimized { "yes" } else { "no" }
    );

    if let Some(casr) = &c.casr {
        let _ = writeln!(
            md,
            "- CASR severity: **{:?}** ({})",
            casr.severity, casr.severity_short
        );
        if !casr.crashline.is_empty() {
            let _ = writeln!(md, "- Crash line: `{}`", casr.crashline);
        }
        if let Some(cluster) = casr.cluster {
            let _ = writeln!(md, "- Cluster: {cluster}");
        }
        if !casr.stack.is_empty() {
            let _ = writeln!(md);
            let _ = writeln!(md, "Stack trace:");
            let _ = writeln!(md);
            let _ = writeln!(md, "```");
            for frame in &casr.stack {
                let _ = writeln!(md, "{frame}");
            }
            let _ = writeln!(md, "```");
        }
    }

    if let Some(report) = &c.bug_report {
        let _ = writeln!(md);
        let _ = writeln!(
            md,
            "**Bug report** (severity guess: {})",
            report.severity_guess
        );
        let _ = writeln!(md);
        if !report.summary.trim().is_empty() {
            let _ = writeln!(md, "{}", report.summary.trim());
            let _ = writeln!(md);
        }
        if !report.repro_steps.trim().is_empty() {
            let _ = writeln!(md, "_Reproduction:_ {}", report.repro_steps.trim());
            let _ = writeln!(md);
        }
    }
    let _ = writeln!(md);
}

// -- AI composition ----------------------------------------------------------

/// System prompt for the LLM that composes the professional narrative report.
#[must_use]
pub fn report_system_prompt() -> &'static str {
    "You are a senior security engineer writing a professional fuzzing campaign \
     report for an engineering and security audience. You write clearly and \
     authoritatively, with concrete, actionable analysis. You NEVER invent facts: \
     every number, severity, file path, and stack frame must come verbatim from \
     the data you are given. If a figure is absent, say it was not measured \
     rather than guessing."
}

/// Build the user prompt: the grounded fact-sheet plus composition rules.
///
/// The fact-sheet (`facts`) is the deterministic [`render_markdown`] output --
/// every real number and the pre-rendered Mermaid graphs -- so the model has no
/// reason to fabricate. The rules pin structure and require the graphs be kept.
#[must_use]
pub fn report_user_prompt(facts: &str, data: &ReportData) -> String {
    format!(
        "Compose a comprehensive, professional fuzzing report in GitHub-flavored \
         Markdown for target `{target}` in project `{project}`.\n\n\
         Use ONLY the facts and figures in the data sheet below. Do not invent \
         crash counts, severities, coverage numbers, file paths, or stack frames. \
         Preserve every ```mermaid``` code block and Markdown table from the data \
         sheet verbatim, placing them in the most relevant section.\n\n\
         Structure the report with these sections (use `##` headings):\n\
         1. Executive Summary - audience-appropriate overview of risk and outcome.\n\
         2. Methodology - engine, sanitizer, duration, corpus, coverage approach.\n\
         3. Coverage Analysis - interpret the coverage figures and what they imply \
         about untested code; include the coverage graphs.\n\
         4. Findings - for EACH crash: a clear title, impact, likely root cause, \
         exploitability rationale (from the CASR severity), and concrete \
         remediation guidance. Include the severity graphs.\n\
         5. Risk Assessment - prioritize the findings and state residual risk.\n\
         6. Recommendations - prioritized, actionable next steps (fixes, more \
         fuzzing, harness/corpus improvements).\n\
         7. Conclusion.\n\n\
         Write in prose, not just bullet lists. Be specific and technical. If \
         there are no crashes, focus on coverage achieved, residual risk, and how \
         to drive deeper.\n\n\
         Output ONLY the Markdown report, starting with a single `#` title. Do not \
         wrap the whole thing in a code fence.\n\n\
         ---\n\
         # DATA SHEET (ground truth)\n\n\
         {facts}",
        target = data.target,
        project = data.project,
    )
}

/// Guarantee the report carries the campaign graphs: if the model's output
/// dropped the Mermaid blocks, append a deterministic Visual Summary so graphs
/// are always present. Also stamps the generator footer.
#[must_use]
pub fn ensure_graphs(ai_markdown: &str, data: &ReportData) -> String {
    let mut out = ai_markdown.trim_end().to_owned();
    if !out.contains("```mermaid") {
        let mut visual = String::new();
        render_visual_summary(&mut visual, data);
        if visual.contains("```mermaid") || visual.contains('█') {
            out.push_str("\n\n");
            out.push_str(&visual);
        }
    }
    let _ = write!(
        out,
        "\n---\n\n_Composed by hobot_fuzz {} on {}._\n",
        data.tool_version, data.generated_at
    );
    out
}

// -- formatting helpers ------------------------------------------------------

fn human_bytes(bytes: u64) -> String {
    if bytes < 1024 {
        return format!("{bytes} B");
    }
    let kb = bytes as f64 / 1024.0;
    if kb < 1024.0 {
        return format!("{kb:.1} KiB");
    }
    format!("{:.1} MiB", kb / 1024.0)
}

fn human_duration(secs: i64) -> String {
    if secs < 60 {
        return format!("{secs}s");
    }
    let m = secs / 60;
    let s = secs % 60;
    if m < 60 {
        return format!("{m}m {s}s");
    }
    let h = m / 60;
    let m = m % 60;
    format!("{h}h {m}m")
}

fn truncate(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_owned();
    }
    let kept: String = s.chars().take(max.saturating_sub(1)).collect();
    format!("{kept}…")
}
